services:
  local-spark:
    image: local-spark  
    container_name: local-spark
    build:
      context: ./
      dockerfile: ./containers/spark/Dockerfile
    environment:
      METADATA_DRIVERNAME: postgresql
      METADATA_HOST: metadata
      METADATA_PORT: '5432'
      METADATA_USERNAME: sdeuser
      METADATA_PASSWORD: sdepassword
      METADATA_DATABASE: metadatadb
    volumes:
      - ./etl:/opt/spark/work-dir/etl 
    depends_on:  
      - metadata
    ports:  
      - "7077:7077" # Spark master submit port, if running
      - "4040:4040" # Spark application
      - "18080:18080" # History server

  metadata:
    image: postgres:16
    container_name: metadata
    environment:
      POSTGRES_USER: sdeuser
      POSTGRES_PASSWORD: sdepassword
      POSTGRES_DB: metadatadb
    ports:
      - "5432:5432"
    volumes:
      - ./containers/metadata/metadata.sql:/docker-entrypoint-initdb.d/init.sql

  minio:
    image: minio/minio:latest
    container_name: minio
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server --console-address ":9001" /data

  prometheus:
    image: prom/prometheus:v3.2.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: [
      "--config.file=/etc/prometheus/prometheus.yml"
    ]
  
  grafana:
    image: grafana/grafana:11.5.2
    container_name: grafana
    ports:
      - "3000:3000"